### ISSUE TITLE
Performance/Lineage excel file generation improvement

### ISSUE THREAD

**Issue by fanninpm** [usafsam/mad_river_wf#11]
This has several tasks with their own justifications:

- ~~Split the `performance_lineage_excel.py` script into two scripts.~~ **EDIT:** Not necessary, as there were originally (and continue to be) separate invocations of the same script.
- [x] Split the `PERFORMANCE_LINEAGE_EXCEL` process into two processes. (#12)
- [x] Remove the Illumina-specific `SampleSheet.csv` requirement from the generation of the lineage excel file. (#12)
- [x] Always generate a lineage excel file. (#12)
- [x] #13
